### PR TITLE
FIX: Remove unused check_performance block.

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
Ready for merge?

**Comment by vsoch** [comment]
Let me know when you are ready for merge @earcanal

**Comment by earcanal** [comment]
Happy if you are. I haven't tested, but I don't see any reference to these blocks so seems safe.. These are odd bits of code review as I'm writing a new Stroop variant based on `stroop-5m`.

**Comment by vsoch** [comment]
I'll double check for you with grep, one sec.

**Comment by vsoch** [comment]
Yep, I don't see them used!

**Pull request merged**
